-- =============================================================================
-- PD Model Demo: Environment Setup Script
-- Run this ONCE before deploying notebooks to set up all infrastructure
-- =============================================================================

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS PD_DEMO_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- DEV environment
CREATE DATABASE IF NOT EXISTS PD_DEMO_DEV;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_DEV.ML;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_DEV.FEATURE_STORE;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_DEV.REGISTRY;

-- STAGING environment
CREATE DATABASE IF NOT EXISTS PD_DEMO_STAGING;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_STAGING.REGISTRY;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_STAGING.SERVING;

-- PROD environment
CREATE DATABASE IF NOT EXISTS PD_DEMO_PROD;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_PROD.REGISTRY;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_PROD.SERVING;
CREATE SCHEMA IF NOT EXISTS PD_DEMO_PROD.MONITORING;

-- Compute pool for SPCS model serving
CREATE COMPUTE POOL IF NOT EXISTS PD_DEMO_CPU_POOL
    MIN_NODES = 1
    MAX_NODES = 3
    INSTANCE_FAMILY = CPU_X64_S
    AUTO_RESUME = TRUE;

-- RBAC roles
CREATE ROLE IF NOT EXISTS PD_DS_DEV;
CREATE ROLE IF NOT EXISTS PD_MLOPS;

-- DS team: full DEV, read STAGING/PROD
GRANT USAGE ON DATABASE PD_DEMO_DEV TO ROLE PD_DS_DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PD_DEMO_DEV TO ROLE PD_DS_DEV;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE PD_DEMO_DEV TO ROLE PD_DS_DEV;
GRANT USAGE ON DATABASE PD_DEMO_STAGING TO ROLE PD_DS_DEV;
GRANT USAGE ON DATABASE PD_DEMO_PROD TO ROLE PD_DS_DEV;

-- ML Ops: full STAGING/PROD, read DEV
GRANT ALL PRIVILEGES ON DATABASE PD_DEMO_STAGING TO ROLE PD_MLOPS;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE PD_DEMO_STAGING TO ROLE PD_MLOPS;
GRANT ALL PRIVILEGES ON DATABASE PD_DEMO_PROD TO ROLE PD_MLOPS;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE PD_DEMO_PROD TO ROLE PD_MLOPS;
GRANT USAGE ON DATABASE PD_DEMO_DEV TO ROLE PD_MLOPS;

GRANT USAGE ON WAREHOUSE PD_DEMO_WH TO ROLE PD_DS_DEV;
GRANT USAGE ON WAREHOUSE PD_DEMO_WH TO ROLE PD_MLOPS;

-- Stage for notebook deployment
CREATE STAGE IF NOT EXISTS PD_DEMO_DEV.ML.NOTEBOOKS
    DIRECTORY = (ENABLE = TRUE);

-- Verify
SELECT 'Setup complete' AS status;
SHOW DATABASES LIKE 'PD_DEMO%';
